///////////////////////////////////////////////////////////////////////////////
// robot_algoClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "robot_algoClassFactory.h"
#include "robot_algoServices.h"
#include "robot_algoVersion.h"
#include "robot_algo.h"

BEGIN_CLASS_MAP(Crobot_algoClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_robot_algo, CID_robot_algoCrobot_algo, SRVNAME_ROBOT_ALGO "!Crobot_algo", Crobot_algo)
///</AutoGeneratedContent>
END_CLASS_MAP()

Crobot_algoClassFactory::Crobot_algoClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ROBOT_ALGO));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(robot_algo));
#endif //defined(TCDBG_UNIT_VERSION)
}

