///////////////////////////////////////////////////////////////////////////////
// robot_algo.h
#pragma once

#include "robot_algoInterfaces.h"

class Crobot_algo 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	Crobot_algo();
	virtual	~Crobot_algo();

///<AutoGeneratedContent id="InterfaceMembers">
///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
///</AutoGeneratedContent>
};


//Eigen::VectorXd poseError(const Eigen::Matrix4d& T_target, const Eigen::Matrix4d& T_current);