///////////////////////////////////////////////////////////////////////////////
// robot_algo.cpp
#include "TcPch.h"
#pragma hdrstop

#include "robot_algo.h"
#include "robot_algoVersion.h"

#include <Eigen/Dense>

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module Crobot_algo
BEGIN_INTERFACE_MAP(Crobot_algo)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(Crobot_algo, VID_robot_algo, CID_robot_algoCrobot_algo)
IMPLEMENT_ITCOMOBJECT(Crobot_algo)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(Crobot_algo)
IMPLEMENT_ITCADI(Crobot_algo)
IMPLEMENT_ITCWATCHSOURCE(Crobot_algo)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of Crobot_algo 
BEGIN_SETOBJPARA_MAP(Crobot_algo)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of Crobot_algo 
BEGIN_GETOBJPARA_MAP(Crobot_algo)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of Crobot_algo
BEGIN_OBJPARAWATCH_MAP(Crobot_algo)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of Crobot_algo
BEGIN_OBJDATAAREA_MAP(Crobot_algo)
///<AutoGeneratedContent id="ObjectDataAreaMap">
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
// Constructor
Crobot_algo::Crobot_algo()
{
///<AutoGeneratedContent id="MemberInitialization">
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
// Destructor
Crobot_algo::~Crobot_algo() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(Crobot_algo)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT Crobot_algo::SetObjStatePS(PTComInitDataHdr pInitData)
{
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT Crobot_algo::SetObjStateSO()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT Crobot_algo::SetObjStateOS()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT Crobot_algo::SetObjStateSP()
{
	HRESULT hr = S_OK;
	return hr;
}


//#include <algorithm>
//#include <chrono>
//#include <stdexcept>
//#include <functional>
#include <Eigen/Dense>
//
//using namespace Eigen;
//
//
//Eigen::VectorXd poseError(
//    const Eigen::Matrix4d& T_target, const Eigen::Matrix4d& T_current) {
//
//    Eigen::Matrix3d R_target = T_target.block<3, 3>(0, 0);
//    Eigen::Matrix3d R_current = T_current.block<3, 3>(0, 0);
//    Eigen::Vector3d t_target = T_target.block<3, 1>(0, 3);
//    Eigen::Vector3d t_current = T_current.block<3, 1>(0, 3);
//
//    // Rotation error
//    Eigen::Matrix3d R_err = R_target - R_current;
//    Eigen::Matrix3d S_w = R_err * R_current.inverse();
//    Eigen::Vector3d V_w(S_w(2, 1), S_w(0, 2), S_w(1, 0));
//
//    // Translation error
//    Eigen::Vector3d V_v = t_target - t_current;
//
//    Eigen::VectorXd error(6);
//    error.head<3>() = V_v;
//    error.tail<3>() = V_w;
//
//    return error;
//}

