///////////////////////////////////////////////////////////////////////////////
// robot_algoInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "robot_algoServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
