///////////////////////////////////////////////////////////////////////////////
// robot_algoServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_robot_algo = 0x3F000000;
#define SRVNAME_ROBOT_ALGO "robot_algo"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_robot_algoCrobot_algo = {0x49c07b84,0x0f2c,0x4ac2,{0x81,0x3f,0xdf,0xb1,0x1e,0x1d,0x53,0x20}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
